//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chemistry.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MendeleevTable
    {
        public int idElement { get; set; }
        public string signElement { get; set; }
        public string nameElement { get; set; }
        public Nullable<double> massElement { get; set; }
    }
}
