//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chemistry.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme
    {
        public int idTheme { get; set; }
        public string nameTheme { get; set; }
        public string infoTheme { get; set; }
    }
}
